### ISSUE TITLE
Mock server: add support for query string in the URL

### ISSUE THREAD

**Issue by nedelcurzvn** [danitseitlin/dmock-server#152]
The Route type needs in addition a property for query string parameters 

node_modules\dmock-server\lib\index.d.ts
`export declare type Route = {
    method: RequestMethod;
    path: string;
    queryStringParameters?: { name: string, values: string[] }[];
    statusCode?: number;
    headers?: {
        [key: string]: any;
    };
    response: {
        [key: string]: any;
    } | ResponseFunction;
};`

**Comment by danitseitlin** [comment]
Query strings are supported and are manageable by the actual response mock function.
Like:
```
{
  "method": "GET",
  "path": "path",
  .....
  .....
  response: (req: Request, res: Response) {
    if(req.params.param1) {
      //do this
    }
  }
}
```

Then I don't really see a reason to want to add it to the Route type.
Can you please elaborate?

**Comment by nedelcurzvn** [comment]
I was referring to the matching URL. It's not exactly the same case, but it can be used as you proposed as well.

**Comment by nedelcurzvn** [comment]
The response function can be used in order to validate the query parameters, so we don't really need an exact matching URL.
